dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-6
      - g++-6
      #- cmake
      - clang
      - libgtest-dev
      - google-mock

before_install:
  - wget https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz
  - tar -xzf cmake-3.8.0.tar.gz
  - export PATH=/usr/local/bin:$PATH
  - export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/:$LD_LIBRARY_PATH

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - cd cmake-3.8.0
    - ./configure
    - make
    - sudo make install
    # gtest install workaround
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/lib/
    - cd /usr/src/gmock
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/lib/
    - cd "${TRAVIS_BUILD_DIR}"

script:
  # Check versions of gcc, g++ and cmake
  - sudo ls /usr/lib/libg*
  - gcc -v && g++ -v && cmake --version
  # build
  - script/build.sh
  # install
  - script/install.sh
  # test
  - script/test.sh

#notifications:
#  email:
#    false